export const customStyles = {
    stepIndicatorSize: 25,
  currentStepIndicatorSize: 30,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: "#ff1493",
  stepStrokeWidth: 3,
  stepStrokeFinishedColor: "#ff1493",
  stepStrokeUnFinishedColor: "#aaaaaa",
  separatorFinishedColor: "#ff1493",
  separatorUnFinishedColor: "#aaaaaa",
  stepIndicatorFinishedColor: "#ff1493",
  stepIndicatorUnFinishedColor: "#ffffff",
  stepIndicatorCurrentColor: "#ffffff",
  stepIndicatorLabelFontSize: 13,
  currentStepIndicatorLabelFontSize: 13,
  stepIndicatorLabelCurrentColor: "#ff1493",
  stepIndicatorLabelFinishedColor: "#ffffff",
  stepIndicatorLabelUnFinishedColor: "#aaaaaa",
  labelColor: "#999999",
  labelSize: 13,
  currentStepLabelColor: "#ff1493"
};